name: 'Publish to GitHub Pages'

env:
  GODOT_VERSION: 4.1.2 # Remember to manually set image to this version below.

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.1.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Install libx11
      #   run: apt-get install -y libx11-6:i386
      - name: Move HTML5 templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Create staging directory and build
        run: |
          mkdir -v -p build/html
          cd testProject
          godot -v --headless --export-release "HTML5" ../build/html/index.html testProject/project.godot

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: html
          path: build/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'

permissions:
  contents: write
