name: 'Publish to GitHub Pages'

env:
  GODOT_VERSION: 4.1.2 # Remember to manually set image to this version below.

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    container:
      image: barichello/godot-ci:4.1.2

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # - name: Install libx11
      #   run: apt-get install -y libx11-6:i386
      - name: Move HTML5 templates into position
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Create staging directory and build
        run: |
          cd testProject
          mkdir -v -p build/html
          godot -v --headless --export-release "Web" build/html/index.html project.godot
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: html
          path: testProject/build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html
          force_orphan: true
          user_name: 'github-ci[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish to gh-pages'
  s3Upload:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: install aws
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: html
      - name: Upload S3
        run: |
          aws s3 sync html s3://max-bow-project

permissions:
  contents: write
